import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import mysql from 'mysql2/promise';
import { cfg, env } from './config.js';
import { db, audit } from './db.js';
import { allocateCpus, allocateMemory, allocatePort } from './allocator.js';
import { serverDir, syncSftp, recreateServer, removeServer } from './docker.js';

const rand = (n = 18) => crypto.randomBytes(n).toString('base64url');
const slug = name => name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 20) || 'server';

export function allLiveServers() {
  return db.prepare(`SELECT * FROM servers WHERE status != 'deleted'`).all();
}

/** Create a server end-to-end: allocation, files, SFTP slot, subscription shell. */
export async function provisionServer(user, w) {
  const slots = Math.min(Math.max(parseInt(w.slots, 10) || 10, 2), 64);
  const cpuset = allocateCpus().join(',');
  const memory_mb = allocateMemory();
  const game_port = allocatePort();

  let id = slug(w.name);
  if (db.prepare(`SELECT 1 FROM servers WHERE id=?`).get(id)) id = `${id}-${rand(3)}`;

  const server = {
    id,
    name: String(w.name || 'CS2 Server').slice(0, 60),
    owner_id: user.id,
    slots,
    game_port,
    cpuset,
    memory_mb,
    gslt: String(w.gslt || '').trim(),
    map: String(w.map || cfg.cs2.default_map),
    game_type: Number.isInteger(+w.game_type) ? +w.game_type : cfg.cs2.default_game_mode.game_type,
    game_mode: Number.isInteger(+w.game_mode) ? +w.game_mode : cfg.cs2.default_game_mode.game_mode,
    sv_password: String(w.sv_password || ''),
    rcon_password: rand(),
    cfg_overrides: JSON.stringify(sanitizeCvars(w.cfg_overrides || {})),
    install_metamod: w.install_metamod === false ? 0 : 1,
    install_cssharp: w.install_cssharp === false ? 0 : 1,
    install_fakercon: w.install_fakercon === false ? 0 : 1,
    install_simpleadmin: w.install_simpleadmin === false ? 0 : 1,
    ftp_user: `bh_${id}`.replace(/-/g, '_').slice(0, 28),
    ftp_password: rand(12),
    status: 'stopped',
    created_at: Date.now(),
  };

  db.prepare(`INSERT INTO servers (id,name,owner_id,slots,game_port,cpuset,memory_mb,gslt,map,game_type,game_mode,
      sv_password,rcon_password,cfg_overrides,install_metamod,install_cssharp,install_fakercon,install_simpleadmin,
      ftp_user,ftp_password,status,created_at)
    VALUES (@id,@name,@owner_id,@slots,@game_port,@cpuset,@memory_mb,@gslt,@map,@game_type,@game_mode,
      @sv_password,@rcon_password,@cfg_overrides,@install_metamod,@install_cssharp,@install_fakercon,@install_simpleadmin,
      @ftp_user,@ftp_password,@status,@created_at)`).run(server);

  db.prepare(`INSERT INTO update_schedules (server_id) VALUES (?)`).run(id);

  // Admins from the wizard (already resolved to steamid64 by the route)
  for (const a of (w.admins || [])) {
    db.prepare(`INSERT OR IGNORE INTO server_admins (server_id, steamid64, label, flags) VALUES (?,?,?,?)`)
      .run(id, a.steamid64, a.label || '', a.flags || '@css/generic');
  }

  writeServerFiles(server);
  if (server.install_simpleadmin) await provisionSimpleAdminDb(server).catch(e =>
    console.warn(`[cs2] SimpleAdmin DB provisioning deferred for ${id}: ${e.message}`));
  await syncSftp(allLiveServers()).catch(e =>
    console.warn(`[cs2] SFTP sync deferred for ${id} (retry from Admin > Re-sync SFTP): ${e.message}`));
  audit(user.id, null, 'server.provisioned', id, { slots, cpuset, memory_mb, game_port });
  return db.prepare(`SELECT * FROM servers WHERE id=?`).get(id);
}

const CVAR_RE = /^[a-z_][a-z0-9_]*$/i;
export function sanitizeCvars(obj) {
  const out = {};
  for (const [k, v] of Object.entries(obj || {})) {
    if (!CVAR_RE.test(k)) continue;
    out[k] = String(v).replace(/[\r\n";]/g, '').slice(0, 120);
  }
  return out;
}

/** Materialize server.cfg + CounterStrikeSharp admins + SimpleAdmin config into the data dir. */
export function writeServerFiles(s) {
  const dir = serverDir(s.id);
  const cfgDir = path.join(dir, 'panel-cfg');
  fs.mkdirSync(cfgDir, { recursive: true });

  const merged = { ...cfg.cs2.default_cfg, ...JSON.parse(s.cfg_overrides || '{}') };
  merged.hostname = merged.hostname || s.name;
  if (s.sv_password) merged.sv_password = s.sv_password;

  const lines = [
    `// Generated by BoneHost — edits here are overwritten. Use custom.cfg for hand edits.`,
    ...Object.entries(merged).map(([k, v]) => `${k} "${v}"`),
    `exec custom.cfg`,
  ];
  fs.writeFileSync(path.join(cfgDir, 'server.cfg'), lines.join('\n') + '\n');
  const customPath = path.join(cfgDir, 'custom.cfg');
  if (!fs.existsSync(customPath)) fs.writeFileSync(customPath, `// Your own cvars — survives every update.\n`);

  // CounterStrikeSharp admins.json
  const admins = db.prepare(`SELECT * FROM server_admins WHERE server_id=?`).all(s.id);
  const adminsJson = {};
  for (const a of admins) {
    adminsJson[a.label || a.steamid64] = { identity: a.steamid64, flags: a.flags.split(',').map(f => f.trim()) };
  }
  fs.writeFileSync(path.join(cfgDir, 'admins.json'), JSON.stringify(adminsJson, null, 2));

  // SimpleAdmin database config (entrypoint copies it into the plugin dir)
  if (s.install_simpleadmin && env.mariadbRootPassword) {
    fs.writeFileSync(path.join(cfgDir, 'simpleadmin.json'), JSON.stringify({
      DatabaseHost: 'bonehost-mariadb',
      DatabasePort: 3306,
      DatabaseUser: s.ftp_user,
      DatabasePassword: s.ftp_password,
      DatabaseName: `sa_${s.id.replace(/-/g, '_')}`,
    }, null, 2));
  }
}

async function provisionSimpleAdminDb(s) {
  if (!env.mariadbRootPassword) throw new Error('MARIADB_ROOT_PASSWORD not set');
  const conn = await mysql.createConnection({
    host: 'bonehost-mariadb', user: 'root', password: env.mariadbRootPassword, connectTimeout: 5000,
  });
  const dbName = `sa_${s.id.replace(/-/g, '_')}`;
  await conn.query(`CREATE DATABASE IF NOT EXISTS \`${dbName}\``);
  await conn.query(`CREATE USER IF NOT EXISTS ?@'%' IDENTIFIED BY ?`, [s.ftp_user, s.ftp_password]);
  await conn.query(`GRANT ALL PRIVILEGES ON \`${dbName}\`.* TO ?@'%'`, [s.ftp_user]);
  await conn.end();
}

export async function applyConfigChanges(s) {
  writeServerFiles(s);
  await recreateServer(s); // picks up env + files; entrypoint re-syncs configs on boot
}

export async function destroyServer(s, actorId) {
  await removeServer(s);
  db.prepare(`UPDATE servers SET status='deleted' WHERE id=?`).run(s.id);
  db.prepare(`UPDATE subscriptions SET status='canceled' WHERE server_id=? AND status != 'canceled'`).run(s.id);
  await syncSftp(allLiveServers());
  audit(actorId, null, 'server.deleted', s.id);
  // Data dir is kept on disk for 30 days of manual recovery; a host cron can purge it.
}
