import crypto from 'node:crypto';
import { cfg, env } from './config.js';
import { db, audit } from './db.js';
import { chooseNode, allocateCpus, allocateMemory, allocatePort, allocateSshPort } from './allocator.js';
import { applyServer, pushFiles, recreateServer, destroyOnNode, provisionSimpleAdmin } from './nodes.js';

const rand = (n = 18) => crypto.randomBytes(n).toString('base64url');
const slug = name => name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 20) || 'server';

export function allLiveServers() {
  return db.prepare(`SELECT * FROM servers WHERE status != 'deleted'`).all();
}

/** Create a server end-to-end: node placement, allocation, files, per-container SSH. */
export async function provisionServer(user, w) {
  const slots = Math.min(Math.max(parseInt(w.slots, 10) || 10, 2), 64);
  const node = chooseNode();
  const cpuset = allocateCpus(node).join(',');
  const memory_mb = allocateMemory(node);
  const game_port = allocatePort(node);
  const ssh_port = allocateSshPort(node);

  let id = slug(w.name);
  if (db.prepare(`SELECT 1 FROM servers WHERE id=?`).get(id)) id = `${id}-${rand(3)}`;

  const server = {
    id,
    node_id: node.id,
    name: String(w.name || 'CS2 Server').slice(0, 60),
    owner_id: user.id,
    slots,
    game_port,
    ssh_port,
    cpuset,
    memory_mb,
    gslt: String(w.gslt || '').trim(),
    map: String(w.map || cfg.cs2.default_map),
    game_type: Number.isInteger(+w.game_type) ? +w.game_type : cfg.cs2.default_game_mode.game_type,
    game_mode: Number.isInteger(+w.game_mode) ? +w.game_mode : cfg.cs2.default_game_mode.game_mode,
    sv_password: String(w.sv_password || ''),
    rcon_password: rand(),
    cfg_overrides: JSON.stringify(sanitizeCvars(w.cfg_overrides || {})),
    install_metamod: w.install_metamod === false ? 0 : 1,
    install_cssharp: w.install_cssharp === false ? 0 : 1,
    install_fakercon: w.install_fakercon === false ? 0 : 1,
    install_simpleadmin: w.install_simpleadmin === false ? 0 : 1,
    ftp_user: `bh_${id}`.replace(/-/g, '_').slice(0, 28),
    ftp_password: rand(12),
    status: 'stopped',
    created_at: Date.now(),
  };

  db.prepare(`INSERT INTO servers (id,node_id,name,owner_id,slots,game_port,ssh_port,cpuset,memory_mb,gslt,map,game_type,game_mode,
      sv_password,rcon_password,cfg_overrides,install_metamod,install_cssharp,install_fakercon,install_simpleadmin,
      ftp_user,ftp_password,status,created_at)
    VALUES (@id,@node_id,@name,@owner_id,@slots,@game_port,@ssh_port,@cpuset,@memory_mb,@gslt,@map,@game_type,@game_mode,
      @sv_password,@rcon_password,@cfg_overrides,@install_metamod,@install_cssharp,@install_fakercon,@install_simpleadmin,
      @ftp_user,@ftp_password,@status,@created_at)`).run(server);

  db.prepare(`INSERT INTO update_schedules (server_id) VALUES (?)`).run(id);

  // Admins from the wizard (already resolved to steamid64 by the route)
  for (const a of (w.admins || [])) {
    db.prepare(`INSERT OR IGNORE INTO server_admins (server_id, steamid64, label, flags) VALUES (?,?,?,?)`)
      .run(id, a.steamid64, a.label || '', a.flags || '@css/generic');
  }

  // Ship files to the node + create the container shell (started only after payment).
  await applyServer(server, { files: buildServerFiles(server), action: 'ensure', start: false }).catch(e =>
    console.warn(`[cs2] node apply deferred for ${id} (re-applies on first start): ${e.message}`));
  if (server.install_simpleadmin) await provisionSimpleAdmin(server).catch(e =>
    console.warn(`[cs2] SimpleAdmin DB provisioning deferred for ${id}: ${e.message}`));
  audit(user.id, null, 'server.provisioned', id, { node: node.id, slots, cpuset, memory_mb, game_port });
  return db.prepare(`SELECT * FROM servers WHERE id=?`).get(id);
}

const CVAR_RE = /^[a-z_][a-z0-9_]*$/i;
export function sanitizeCvars(obj) {
  const out = {};
  for (const [k, v] of Object.entries(obj || {})) {
    if (!CVAR_RE.test(k)) continue;
    out[k] = String(v).replace(/[\r\n";]/g, '').slice(0, 120);
  }
  return out;
}

/**
 * Materialize server.cfg + CounterStrikeSharp admins + SimpleAdmin config as a
 * {relative_path: content} map. The agent writes it into the node's data dir;
 * custom.cfg is create-only on the agent side so hand edits survive.
 */
export function buildServerFiles(s) {
  const files = {};
  const merged = { ...cfg.cs2.default_cfg, ...JSON.parse(s.cfg_overrides || '{}') };
  merged.hostname = merged.hostname || s.name;
  if (s.sv_password) merged.sv_password = s.sv_password;

  files['panel-cfg/server.cfg'] = [
    `// Generated by BoneHost — edits here are overwritten. Use custom.cfg for hand edits.`,
    ...Object.entries(merged).map(([k, v]) => `${k} "${v}"`),
    `exec custom.cfg`,
  ].join('\n') + '\n';

  files['panel-cfg/custom.cfg'] = `// Your own cvars — survives every update.\n`; // agent skips if it exists

  const admins = db.prepare(`SELECT * FROM server_admins WHERE server_id=?`).all(s.id);
  const adminsJson = {};
  for (const a of admins) {
    adminsJson[a.label || a.steamid64] = { identity: a.steamid64, flags: a.flags.split(',').map(f => f.trim()) };
  }
  files['panel-cfg/admins.json'] = JSON.stringify(adminsJson, null, 2);

  // Optional subscriber SSH key (dashboard-managed); null deletes it on the node.
  files['panel-cfg/authorized_keys'] = s.ssh_pubkey?.trim() ? s.ssh_pubkey.trim() + '\n' : null;

  if (s.install_simpleadmin && env.mariadbRootPassword) {
    files['panel-cfg/simpleadmin.json'] = JSON.stringify({
      DatabaseHost: 'bonehost-mariadb', // node-local MariaDB, reachable on the node's docker network
      DatabasePort: 3306,
      DatabaseUser: s.ftp_user,
      DatabasePassword: s.ftp_password,
      DatabaseName: `sa_${s.id.replace(/-/g, '_')}`,
    }, null, 2);
  }
  return files;
}

/** Push regenerated files to the node without touching the container. */
export function writeServerFiles(s) {
  return pushFiles(s, buildServerFiles(s)).catch(e =>
    console.warn(`[cs2] file push deferred for ${s.id}: ${e.message}`));
}

export async function applyConfigChanges(s) {
  await recreateServer(s, [], buildServerFiles(s)); // fresh files + fresh container in one call
}

export async function destroyServer(s, actorId) {
  await destroyOnNode(s).catch(e => console.warn(`[cs2] node destroy deferred for ${s.id}: ${e.message}`));
  db.prepare(`UPDATE servers SET status='deleted' WHERE id=?`).run(s.id);
  db.prepare(`UPDATE subscriptions SET status='canceled' WHERE server_id=? AND status != 'canceled'`).run(s.id);
  audit(actorId, null, 'server.deleted', s.id);
  // The node keeps the data dir for 30 days of manual recovery; a node cron can purge it.
}
